name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/pretsbarnabas/jsondb-editor:$IMAGE_TAG --tag ghcr.io/pretsbarnabas/jsondb-editor:latest
        docker login ghcr.io --username pretsbarnabas --password ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/pretsbarnabas/jsondb-editor:$IMAGE_TAG
        docker push ghcr.io/pretsbarnabas/jsondb-editor:latest
        
